apiVersion: v1
kind: Service
metadata:
  name: springboot-app
  labels:
    app: springboot-app
spec:
  type: NodePort
  selector:
    component: springboot-app
  ports:
  - name: http
    port: 8080
    protocol: TCP
