apiVersion: v1
kind: ReplicationController
metadata:
  name: springboot-app
spec:
  replicas: 1
  selector:
    app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
      - name: springboot-app
        image: bankmonitor/spring-boot:latest
        ports:
        - containerPort: 8080
