apiVersion: v1
kind: ReplicationController
metadata:
  name: rabbitmq
  labels:
    component: rabbitmq
spec:
  replicas: 1
  selector:
    app: rabbitmq
  template:
    metadata:
      name: rabbitmq
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.5.7-management
        ports:
        - containerPort: 5672
